<?php
/**
 * This script gets the current table layout of every table in the
 * Übersite database and writes the CREATE TABLE statements to
 * setup/database.sql. You should run this script every time you alter,
 * create or drop a table.
 *
 * The output returned is identical to the output of SHOW CREATE TABLE for
 * every table, with one exception: the AUTO_INCREMENT value is removed.
 */

if (PHP_SAPI != "cli") {
  echo "<div style='font-family: Consolas, \"Liberation Sans\", courier, monospace'>";
  echo "This script must be run via the command line.";
  exit;
}

require_once("../camp-data/config/database.php");
echo "\nConnecting to database $MYSQL_HOST/$MYSQL_DATABASE...\n";

$mysql = new MySQLi($MYSQL_HOST, $MYSQL_USER, $MYSQL_PASSWORD, $MYSQL_DATABASE);
$result = $mysql->query("SHOW TABLES");

echo "{$result->num_rows} tables found.\n\n";
echo "Generating CREATE TABLE statements...\n";

$versionFile = json_decode(file_get_contents("../includes/version.json"), true);
$version = $versionFile["softwareVersion"];

$fileContent = "--\n-- Generated by UberSite $version.\n-- ".date("r")."\n--\n\n";

$count = 0;
while ($table = $result->fetch_row()[0]) {
  $count++;
  printf("%2d. %s ", $count, $table);

  $createQuery = $mysql->query("SHOW CREATE TABLE `$table`")->fetch_row()[1];

  $fileContent .= "--\n-- Definition of table `$table`\n--\n\n";
  $fileContent .= $createQuery . "\n\n";
  echo "\n";
}

$fileContent = preg_replace('/AUTO_INCREMENT=\d+ /', '', $fileContent);
echo "\nSaving to ../setup/database.sql ...";
file_put_contents("../setup/database.sql", $fileContent);
echo " all done!\n\n";
echo "Don't forget to push the updated file to git.\n\n";
?>